(() => {
 'use strict';
 const A=()=>RombiesApp;let tab='team',selected=0,wave=0,enemy=0,obstacle=0,dirty=false;
 function changed(){dirty=true;}
 function open(){
  const a=A();if(!a.draft)a.draft=ROMBIES_CHAPTER2.template();const d=a.draft;const {$,button,field,select}=a;
  const wrap=a.view();a.top(wrap,'Sandbox / Fight builder',()=>leave(),()=>leave(a.legacy));
  const toolbar=$('div',{class:'ex-actions',style:'margin-bottom:18px'});toolbar.append(button('▶ Playtest',()=>{try{a.playFight(RombiesSchema.fight(d),{exit:open});}catch(e){a.status(e.message,true);}},'primary'),button('Save draft',()=>{try{a.saveDraft(d);dirty=false;}catch(e){a.status(e.message,true);}}),button(a.editId?'Update published fight':'Publish to Discover',publish),button('Export fight',exportFight),button('Import fight',importFight));wrap.append(toolbar);
  const layout=$('div',{class:'ex-editor'}),side=$('aside',{class:'ex-sidebar'}),main=$('div',{class:'ex-editor-main'});layout.append(side,main);wrap.append(layout);
  side.append($('span',{class:'ex-mini-label',text:'FIGHT SETTINGS'}));for(const [id,name] of [['details','Title & rules'],['team','Your team'],['waves','Enemies & waves'],['arena','Arena & obstacles']])side.append(button(name,()=>{tab=id;open();},tab===id?'active':''));side.append($('p',{class:'ex-muted',text:'Playtest as often as you like. Publishing shares a playable copy; drafts stay on this browser.'}));
  if(tab==='details'){
   main.append(section('Name your chaos',[$('div',{class:'ex-form'},[field('Fight name',d.title,v=>{d.title=v;changed();},'text',{maxlength:80}),select('Win condition',d.mode,[['defeat','Defeat all waves'],['survive','Survive the timer'],['bossrush','Boss rush']],v=>{d.mode=v;changed();}),field('Description (optional)',d.description,v=>{d.description=v;changed();},'textarea',{maxlength:1000,wide:true}),field('Survival duration (seconds)',d.duration,v=>{d.duration=v;changed();},'number',{min:15,max:600}),field('Gravity',d.gravity,v=>{d.gravity=v;changed();},'number',{min:500,max:2000,step:50}),field('Player damage multiplier',d.playerDamage,v=>{d.playerDamage=v;changed();},'number',{min:.3,max:3,step:.1}),field('Enemy damage multiplier',d.enemyDamage,v=>{d.enemyDamage=v;changed();},'number',{min:.3,max:3,step:.1}),field('Friendly fire',d.friendlyFire,v=>{d.friendlyFire=v;changed();},'checkbox'),select('Music',d.music,['culling','pyramid','chaos','finale','quiet'],v=>{d.music=v;changed();}),field('Arena accent',d.color,v=>{d.color=v;changed();},'color')]) ]));
  }
  if(tab==='team'){
   selected=Math.min(selected,d.party.length-1);const list=$('div',{class:'ex-list'});d.party.forEach((f,i)=>list.append(fighterRow(f,()=>{selected=i;open();},()=>{if(d.party.length>1){d.party.splice(i,1);selected=0;changed();open();}})));
   main.append(section('Your team',[$('p',{class:'ex-muted',text:'Up to four characters. Switch between living teammates with Tab.'}),list,button('+ Add teammate',()=>{if(d.party.length>=4){a.status('Four teammates is the maximum.');return;}d.party.push(structuredClone(ROMBIES_CHAPTER2.roster.shane));selected=d.party.length-1;changed();open();})]));
   main.append(fighterEditor(d.party[selected],f=>{d.party[selected]=f;changed();open();}));
  }
  if(tab==='waves'){
   wave=Math.min(wave,d.waves.length-1);enemy=Math.min(enemy,d.waves[wave].enemies.length-1);const tabs=$('div',{class:'ex-actions'});d.waves.forEach((w,i)=>tabs.append(button((i+1)+'. '+w.name,()=>{wave=i;enemy=0;open();},i===wave?'active':'')));
   tabs.append(button('+ Wave',()=>{if(d.waves.length>=8){a.status('Eight waves is the maximum.');return;}d.waves.push({name:'Wave '+(d.waves.length+1),delay:2,enemies:[structuredClone(ROMBIES_CHAPTER2.roster.rombie)]});wave=d.waves.length-1;enemy=0;changed();open();}));
   const w=d.waves[wave],list=$('div',{class:'ex-list'});w.enemies.forEach((f,i)=>list.append(fighterRow(f,()=>{enemy=i;open();},()=>{if(w.enemies.length>1){w.enemies.splice(i,1);enemy=0;changed();open();}})));
   main.append(section('Enemy waves',[tabs,$('div',{class:'ex-form',style:'margin:16px 0'},[field('Wave name',w.name,v=>{w.name=v;changed();},'text',{maxlength:48}),field('Delay before this wave',w.delay,v=>{w.delay=v;changed();},'number',{min:0,max:15,step:.5})]),list,$('div',{class:'ex-actions',style:'margin-top:12px'},[button('+ Enemy',()=>{if(w.enemies.length>=8){a.status('Eight enemies per wave is the maximum.');return;}w.enemies.push(structuredClone(ROMBIES_CHAPTER2.roster.rombie));enemy=w.enemies.length-1;changed();open();}),button('Duplicate wave',()=>{if(d.waves.length<8){d.waves.splice(wave+1,0,structuredClone(w));wave++;changed();open();}}),button('Remove wave',()=>{if(d.waves.length>1){d.waves.splice(wave,1);wave=0;enemy=0;changed();open();}},'danger')])]));
   main.append(fighterEditor(w.enemies[enemy],f=>{w.enemies[enemy]=f;changed();open();}));
  }
  if(tab==='arena'){
   const preview=$('canvas',{class:'ex-preview',width:1280,height:720,'aria-label':'Arena layout. Drag obstacles to reposition them.'});
   main.append(section('Arena',[assetButton('Background',d.background,'background',v=>{d.background=v;changed();open();}),$('p',{class:'ex-muted',text:'Drag obstacles in the preview. Platforms can be jumped onto; cover blocks shots and breaks; hazards deal damage; healing zones restore health.'}),preview]));
   const ctx=preview.getContext('2d');a.setFrame(()=>{ctx.fillStyle='#132230';ctx.fillRect(0,0,1280,720);RombiesMedia.draw(ctx,d.background,0,0,1280,720,'cover');ctx.fillStyle='#10213266';ctx.fillRect(0,600,1280,120);ctx.fillStyle=d.color;ctx.fillRect(0,600,1280,3);for(const [i,o] of d.obstacles.entries()){ctx.fillStyle=o.color;ctx.globalAlpha=.7;ctx.fillRect(o.x,o.y,o.w,o.h);ctx.globalAlpha=1;if(o.asset)RombiesMedia.draw(ctx,o.asset,o.x,o.y,o.w,o.h,'stretch');ctx.strokeStyle=i===obstacle?'#fff':'#999';ctx.lineWidth=i===obstacle?5:2;ctx.strokeRect(o.x,o.y,o.w,o.h);ctx.font='18px Arial';ctx.fillStyle='#fff';ctx.fillText(o.name,o.x,o.y-8);}d.party.forEach((f,i)=>RombiesMedia.draw(ctx,f.sprite,110+i*95,445,115,155));});
   let dragging=null;const point=e=>{const r=preview.getBoundingClientRect();return {x:(e.clientX-r.left)/r.width*1280,y:(e.clientY-r.top)/r.height*720};};
   preview.onpointerdown=e=>{const p=point(e);const index=d.obstacles.findLastIndex(o=>p.x>=o.x&&p.x<=o.x+o.w&&p.y>=o.y&&p.y<=o.y+o.h);if(index>=0){obstacle=index;const o=d.obstacles[index];dragging={o,dx:p.x-o.x,dy:p.y-o.y};preview.setPointerCapture(e.pointerId);}};
   preview.onpointermove=e=>{if(dragging){const p=point(e);dragging.o.x=Math.round(RombiesSchema.clamp(p.x-dragging.dx,30,1190));dragging.o.y=Math.round(RombiesSchema.clamp(p.y-dragging.dy,200,610));changed();}};
   preview.onpointerup=()=>{if(dragging){dragging=null;open();}};preview.onpointercancel=()=>dragging=null;
   const list=$('div',{class:'ex-actions'});d.obstacles.forEach((o,i)=>list.append(button(o.name,()=>{obstacle=i;open();},i===obstacle?'active':'')));list.append(button('+ Obstacle',()=>{if(d.obstacles.length>=24){a.status('24 obstacles is the maximum.');return;}d.obstacles.push({id:crypto.randomUUID(),name:'Cover '+(d.obstacles.length+1),type:'cover',x:550,y:490,w:95,h:110,color:'#8cb9b1',asset:'',hp:250,damage:12});obstacle=d.obstacles.length-1;changed();open();}));main.append(section('Obstacles',[list]));
   if(d.obstacles.length){obstacle=Math.min(obstacle,d.obstacles.length-1);const o=d.obstacles[obstacle];main.append(section('Edit obstacle',[$('div',{class:'ex-form'},[field('Name',o.name,v=>{o.name=v;changed();},'text',{maxlength:32}),select('Type',o.type,['cover','platform','hazard','heal','bounce'],v=>{o.type=v;changed();}),...['x','y','w','h','hp','damage'].map(k=>field({x:'X position',y:'Y position',w:'Width',h:'Height',hp:'Cover durability',damage:'Damage / healing per second'}[k],o[k],v=>{o[k]=v;changed();},'number',{min:0,max:k==='hp'?2000:1280})),field('Color',o.color,v=>{o.color=v;changed();},'color')]),assetButton('Obstacle artwork',o.asset,'obstacle',v=>{o.asset=v;changed();open();}),$('div',{class:'ex-actions',style:'margin-top:12px'},[button('Clear artwork',()=>{o.asset='';changed();open();}),button('Remove obstacle',()=>{d.obstacles.splice(obstacle,1);obstacle=0;changed();open();},'danger')])]));}
  }
 }
 function section(title,children){const {$}=A();return $('section',{class:'ex-section'},[$('h2',{text:title}),...children]);}
 function fighterRow(f,edit,remove){const a=A();return a.$('div',{class:'ex-fighter-row'},[a.image(f.sprite),a.$('span',{text:f.name}),a.button('Edit',edit),a.button('−',remove)]);}
 function fighterEditor(f,replace){
  const a=A(),{$,field,select,button}=a;const choices=Object.entries(ROMBIES_CHAPTER2.roster).map(([id,r])=>[id,r.name]);const preset=select('Start from a Rombies character','', [['','Choose preset…'],...choices],id=>{if(id)replace(structuredClone(ROMBIES_CHAPTER2.roster[id]));});
  const controls=$('div',{class:'ex-form'},[preset,field('Character name',f.name,v=>{f.name=v;changed();},'text',{maxlength:32}),field('Health',f.hp,v=>{f.hp=v;changed();},'number',{min:50,max:5000,step:50}),field('Movement speed',f.speed,v=>{f.speed=v;changed();},'number',{min:70,max:500,step:10}),field('Sprite scale',f.size,v=>{f.size=v;changed();},'number',{min:.45,max:2.6,step:.05}),select('AI behavior',f.ai,['balanced','rush','ranged','tank','support'],v=>{f.ai=v;changed();}),field('Character aura color',f.color,v=>{f.color=v;changed();},'color')]);
  const out=section(f.name,[controls,assetButton('Character sprite',f.sprite,'character',v=>{f.sprite=v;changed();open();}),$('h3',{text:'Attack loadout'})]);const moveGrid=$('div',{class:'ex-move-grid'});f.moves.forEach((m,i)=>moveGrid.append(moveEditor(m,'Attack '+(i+1))));out.append(moveGrid,moveEditor(f.ultimate,'Ultimate · earned during combat'));return out;
 }
 function moveEditor(m,label){const a=A(),{$,field,select}=a;return $('details',{class:'ex-section'},[$('summary',{text:label+' · '+m.name,style:'cursor:pointer;font-weight:700;margin-bottom:12px'}),$('div',{class:'ex-form'},[field('Attack name',m.name,v=>{m.name=v;changed();},'text',{maxlength:32}),select('Behavior',m.kind,RombiesSchema.kinds,v=>{m.kind=v;changed();}),field('Color',m.color,v=>{m.color=v;changed();},'color'),select('Status effect',m.effect,RombiesSchema.effects,v=>{m.effect=v;changed();}),...Object.entries({damage:['Damage / healing',0,150,.5],cooldown:['Cooldown (seconds)',.25,30,.25],speed:['Projectile speed',100,1200,25],size:['Projectile / beam size',6,100,1],range:['Range',60,1100,20],count:['Projectile count',1,7,1],spread:['Spread',0,1.8,.1],duration:['Effect duration',.2,8,.2]}).map(([k,[title,min,max,step]])=>field(title,m[k],v=>{m[k]=v;changed();},'number',{min,max,step})),field('Pierce through characters',m.pierce,v=>{m.pierce=v;changed();},'checkbox')]),assetButton('Projectile artwork (optional)',m.asset,'attack',v=>{m.asset=v;changed();open();}),a.button('Use color only',()=>{m.asset='';changed();open();})]);}
 function assetButton(label,key,kind,change){const a=A();return a.$('button',{class:'ex-asset-button',type:'button',style:'margin:13px 0',onclick:()=>assetPicker(kind,change)},[key?a.image(key):a.$('span',{text:'＋',style:'font-size:30px;width:60px;text-align:center'}),a.$('span',{text:label+' · choose or upload'})]);}
 async function assetPicker(kind,choose){
  const a=A(),{$,button}=a;let search='',category=kind==='background'?'backgrounds':'characters';const grid=$('div',{class:'ex-library'}),note=$('p',{class:'ex-muted',text:'Uploads are compressed automatically. Custom artwork stays local until you publish.'});
  const file=$('input',{type:'file',accept:'image/png,image/jpeg,image/webp',hidden:true});file.onchange=async()=>{if(!file.files[0])return;note.textContent='Compressing artwork…';try{const result=await RombiesMedia.compress(file.files[0],kind);a.closeDialog();choose(result.id);}catch(e){note.textContent=e.message;}};
  const stock={characters:Object.entries(ROMBIES_CHAPTER2.roster).map(([k,f])=>({key:f.sprite,name:f.name})),backgrounds:Object.entries(ASSETS.bgs).map(([k])=>({key:'bg:'+k,name:k.replaceAll('_',' ')})).concat(ROMBIES_CHAPTER2.backgrounds),effects:Object.entries(ASSETS.fx).map(([k])=>({key:'fx:'+k,name:k.replaceAll('_',' ')})),all:Object.entries(ROMBIES_ART).map(([k])=>({key:k,name:'Chapter Two '+k})),local:[]};
  const render=()=>{grid.replaceChildren();for(const item of stock[category].filter(x=>x.name.toLowerCase().includes(search.toLowerCase())).slice(0,200)){const b=$('button',{type:'button',onclick:()=>{a.closeDialog();choose(item.key);}},[a.image(item.key),$('span',{text:item.name})]);grid.append(b);}if(!grid.childElementCount)grid.append($('p',{text:'No artwork found.'}));};
  a.showDialog('Choose '+kind+' artwork',[$('div',{class:'ex-form'},[a.field('Search',search,v=>{search=v;render();}),a.select('Library',category,[['characters','Characters'],['backgrounds','Backgrounds'],['effects','Attacks & effects'],['all','All Chapter Two art'],['local','My uploads']],v=>{category=v;render();})]),note,button('Upload image',()=>file.click(),'primary'),file,grid],[button('Cancel',a.closeDialog)]);render();
  try{stock.local=(await RombiesMedia.all()).map(x=>({key:x.id,name:x.name}));if(category==='local')render();}catch(_){}
 }
 async function publish(){
  const a=A();let cfg;try{cfg=RombiesSchema.fight(a.draft);}catch(e){a.status(e.message,true);return;}
  const text=a.$('p',{text:'Publish this fight so everyone can find and play it in Discover. Custom images will be uploaded to your R2 library.'});
  const submit=a.button(a.editId?'Update fight':'Publish fight',async()=>{submit.disabled=true;try{let profile=await RombiesCloud.getProfile();if(!profile){if(!a.profile)throw Error('Create your username from the Sandbox menu first.');profile=await RombiesCloud.claim(a.profile.handle,a.profile.displayName);}cfg=await RombiesMedia.publishAssets(cfg,s=>text.textContent=s);text.textContent='Saving your fight…';a.editId=await RombiesCloud.publish(cfg,a.editId,true);a.draft=cfg;dirty=false;a.closeDialog();a.saveDraft(cfg);a.sandbox('mine');a.status('Published! Your fight is available in Discover.');}catch(e){text.textContent=RombiesCloud.explain(e);submit.disabled=false;}},'primary');a.showDialog('Publish '+cfg.title,[text],[a.button('Cancel',a.closeDialog),submit]);
 }
 async function exportFight(){
  const a=A();try{const cfg=RombiesSchema.fight(a.draft),ids=[...new Set(JSON.stringify(cfg).match(/local:[a-f0-9-]{36}/gi)||[])],art={};let total=0;
   for(const id of ids){const item=await RombiesMedia.local(id);if(!item)throw Error('A custom image is missing.');total+=item.blob.size;if(total>12*1024*1024)throw Error('This fight’s images exceed 12 MB. Publish it or use fewer custom images.');art[id]={kind:item.kind,name:item.name,data:await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(item.blob);})};}
   a.download({format:'rombies-fight-1',config:cfg,art},'rombies-fight.json');dirty=false;
  }catch(e){a.status(e.message,true);}
 }
 function importFight(){const a=A(),input=a.$('input',{type:'file',accept:'.json,application/json'});input.onchange=async()=>{try{const file=input.files[0];if(!file)return;if(file.size>18*1024*1024)throw Error('Fight import must be under 18 MB.');const data=JSON.parse(await file.text());let cfg=RombiesSchema.fight(data.config||data);if(data.format==='rombies-fight-1'&&data.art){let text=JSON.stringify(cfg),count=0;for(const [id,item] of Object.entries(data.art)){if(++count>40)throw Error('Too many imported images.');if(!text.includes(id))continue;if(typeof item.data!=='string'||item.data.length>2900000||!/^data:image\/(webp|png|jpeg);base64,/.test(item.data))throw Error('Invalid embedded image.');const blob=await (await fetch(item.data)).blob();const file=new File([blob],String(item.name||'imported.webp').slice(0,70),{type:blob.type});const out=await RombiesMedia.compress(file,['background','character','attack','obstacle'].includes(item.kind)?item.kind:'character');text=text.replaceAll(id,out.id);}cfg=RombiesSchema.fight(JSON.parse(text));}a.draft=cfg;a.editId=null;a.draftId=null;dirty=true;open();a.status('Fight imported. Playtest it or save a local draft.');}catch(e){a.status(e.message,true);}};input.click();}
 function leave(destination){const a=A(),done=destination||(()=>a.sandbox('drafts'));if(!dirty){done();return;}a.showDialog('Save your changes?',[a.$('p',{text:'Save a draft to keep these changes on this browser.'})],[a.button('Keep editing',a.closeDialog),a.button('Save & leave',()=>{try{a.saveDraft(a.draft);dirty=false;done();}catch(e){a.status(e.message,true);}},'primary'),a.button('Leave without saving',()=>{dirty=false;done();})]);}
 window.RombiesEditor={open};
})();
